export default {
  // Header
  "Welcome to": "Welcome to",
  "tryDemo": "It's the new uPort Serto demo where enterprises, businesses, and services create a trusted ecosystem to provide a seamless experience to their customers.",
  "Get Started": "Get Started",
  "Store it in the uport app": "Store it in the uPort app",
  "Own your information": "Manage your personal data. You decide when and with whom you share it.",
  "Get access to many services": "Get access to many services.",
  "Enjoy perks and benefits": "Enjoy the perks and benefits of getting access to services with one click.",
  "Ready? Lets do this": "Ready? Let's do this!",
  "Who it's for": "Who it's for",
  "Customers like Monica": "Customers, like Monica.",
  "Monica loves driving": "Monica loves driving. She wants to buy a car and become a driver for a ride sharing service. She’s also hoping to get into the employee stock options purchase plan for drivers. This way she can have a stake in the growing ride-share company.",
  "Be like Monica": "Be like Monica. Try out uPort for yourself",
  "How it works": "How it works",
  "Collect your credentials": "Collect your credentials",
  "Receive your identity verification with one click": "Receive your identity and personal data verified with only a few clicks.",

  // AppDownload
  "make sure you have your phone handy": "Psst... Make sure you have your phone handy with the uPort app downloaded.",
  "make sure you have the uport app downloaded": "Psst... Make sure you have the uPort app downloaded",

  // ServiceCard"
  "youll be asked to share": "You'll be asked to share",
  "credential included": "credential included",
  "credentials included": "credentials included",
  "credentials included in": "Credentials included in",
  "getClaimLabel": "Get",

  // Footer
  "Powered by": "Powered by",

  "Vericheck Identity Verifier": "Vericheck Identity Verifier",
  "driversLicenseDisplayName": "Driver's License",
  "driversLicenseDescription": "Identify yourself with one click. Get your digital driver license via Vericheck. Start enjoying all the services the ecosystem has to offer.",
  "driversLicenseStep1": "Login with uPort",
  "driversLicenseStep2": "Enter your information",
  "driversLicenseStep3": "Get verified",
  "driversLicenseStep4": "Receive Driver's License",

  "Mappe Maps & Navigation": "Mappe Maps & Navigation",
  "Number of Accidents": "Number of Accidents",
  "Number of Speeding Violations": "Number of Speeding Violations",
  "safeDriverDisplayName": "Safe Driver Badge",
  "safeDriverDescription": "Have you been driving with Mappe for a while and never had an accident? Get your Safe Driver Badge and use it with other services and platforms.",
  "safeDriverStep1": "Login with uPort",
  "safeDriverStep2": "Get verified",
  "safeDriverStep3": "Get Badge",
  "safeDriverHeading": "Get credit for good driving!",
  "safeDriverDetail1": "Receive proof of being a responsible driver.",
  "safeDriverDetail2": "Use your Safe Driver Badge to get access to other services and perks that reward safe drivers.",

  "Simple Fund Bank": "Simple Fund Bank",
  "Finance up to": "Finance up to",
  "Annual Percentage Rate": "Annual Percentage Rate",
  "Valid Through": "Valid Through",
  "carLoanDisplayName": "Car Loan Qualification",
  "carLoanDescription": "Apply for a Car Loan with your Identity Verification and get pre-qualified instantly. Share your Safe Driver Badge to get a better interest rate.",
  "carLoanStep1": "Login with uPort",
  "carLoanStep2": "Get verified",
  "carLoanStep3": "Get Qualified",
  "carLoanHeading": "Pre-qualification is just seconds away!",
  "carLoanDetail1": "Speed up your loan process by getting pre-qualified for a car loan.",
  "carLoanDetail2": "Use your driving reputation to breeze through the car buying process.",

  "McQuinn Car Dealership": "McQuinn Car Dealership",
  "Vehicle ID Number": "Vehicle ID Number",
  "Vehicle Make": "Vehicle Make",
  "Vehicle Model": "Vehicle Model",
  "Year": "Year",
  "Plate Number": "Plate Number",
  "Owner": "Owner",
  "carDealerDisplayName": "Car Title",
  "carDealerDescription": "Walk in and drive away! Forget about tedious paperwork and formalities. Get your Car Loan approved away... and drive away in your new car.",
  "carDealerStep1": "Login with uPort",
  "carDealerStep2": "Get verified",
  "carDealerStep3": "Get Title",
  "carDealerHeading": "It's time for an upgrade.",
  "carDealerDetail1": "Upgrade the experience for both yourself and your riders.",
  "carDealerDetail2": "Find the car of your dreams and walk off the lot in minutes.",

  "Better Safe Insurance Company": "Better Safe Insurance Company",
  "Policy Number": "Policy Number",
  "Status": "Status",
  "insuranceDisplayName": "Car Insurance",
  "insuranceDescription": "Yes, you need Car Insurance. Get it with just one click. Prove that you're a responsible driver and get a discount on your monthly rate by sharing your Safe Driver Badge.",
  "insuranceStep1": "Login with uPort",
  "insuranceStep2": "Get verified",
  "insuranceStep3": "Get Proof of Insurance",
  "insuranceHeading": "Better safe than sorry!",
  "insuranceDetail1": "Make sure you are covered in case of an accident!",
  "insuranceDetail2": "Get the best rates by sharing your driving reputation.",

  "Ride Away Ride-Sharing App": "Ride Away Ride-Sharing App",
  "Account Name": "Account Name",
  "Date Joined": "Date Joined",
  "rideSharingDisplayName": "Driver Verification",
  "rideSharingDescription": "Become a Ride Away Driver and make money on your own time. But, don't build your score from scratch! Boost your driver score with reputation credentials from other services and platforms that you already have stored in your uPort app.",
  "rideSharingStep1": "Login with uPort",
  "rideSharingStep2": "Get verified",
  "rideSharingStep3": "Get Driver Verification",
  "rideSharingHeading": "Make money on your time!",
  "rideSharingDetail1": "Start earning money and work the hours you want by becoming a Ride Away Driver.",
  "rideSharingDetail2": "Earn better and better rates and perks as your improve your driver reputation.",

  "Ride Away Stock Purchase Plan": "Ride Away Stock Purchase Plan",
  "Stock Price": "Stock Price",
  "Purchase Price": "Purchase Price",
  "Contribution Level Guaranteed": "Contribution Level Guaranteed",
  "investmentsDisplayName": "Ride Away Employee Stock Purchase Plan",
  "investmentsDescription": "Invest in Ride Away and grow with the businesses you believe in. Ride Away doubles investments made by both riders and drivers!",
  "investmentsStep1": "Login with uPort",
  "investmentsStep2": "Get verified",
  "investmentsStep3": "Get Purchase Plan Credential",
  "investmentsHeading": "Get a stake in Ride Away's success!",
  "investmentsDetail1": "Don't just drive for Ride Away, get a stake in the company's future.",
  "investmentsDetail2": "Prove your Driver history with Ride Away and get access to the employee stock purchase plan!",

  "First Name": "First Name",
  "Last Name": "Last Name",
  "Address": "Address",
  "Date of Birth": "Date of Birth",

  "Driver's License": "Driver's License",
  "Safe Driver Badge": "Safe Driver Badge",
  "Qualifies for Car Loan": "Qualifies for Car Loan",
  "Get Qualified": "Get Qualified",
  "Car Title Claim 1": "Car Title Claim 1",
  "Car Title Claim 2": "Car Title Claim 2",
  "Get Brand New Car": "Get Brand New Car",
  "Car Insurance": "Car Insurance",
  "Driver Verification": "Driver Verification",
  "Global Capital Investments": "Global Capital Investments",
  "Learn More About Serto Ecosystem": "Learn More About Serto Ecosystems",

  "get your": "Get your",
  "Receive your": "Receive your",
  "back": "Back",
  "Login with uPort": "Login with uPort",
  "will ask you to share": "will ask you to share",
  "Your claims were succesfully shared with": "Your claims were succesfully shared with",
  "is going to send your new claims to your uPort app": "",

  "regnLandingHeading": "Get ready to hit the road!",
  "regnLandingStep1": "Get things done without leaving your home. No more standing in lines.",
  "regnLandingStep2": "Access services and programs offered by the ecosystem.",
  "regnLandingStep3": "Start driving today!",

  // Home
  "Step 1": "Step 1",
  "Step 2": "Step 2",
  "Step 3": "Step 3",
  "Step 4": "Step 4",
  "Prove your identity": "Prove your identity",
  "To kick off the process get a proof of your driver's license": "To kick off the process get a digital proof of your driver's license",
  "Buy a new car": "Buy a new car",
  "You can get it right away or get a loan for it": "You can get it right away by paying out-of-pocket, or... get a loan for it! To get approved for the loan and receive a better interest rate, you can now share a proof from your navigation system that you drive safely!",
  "Become a driver": "Become a driver",
  "Become a Driver": "Become a Driver",
  "To drive other passengers you need car insurance": "To become a driver in a ride-sharing service, you will need car insurance. Luckily, you've already got all the required documents stored in your uPort app. All you need to do is apply!",
  "Become a shareholder": "Become a shareholder",
  "Become a Shareholder": "Become a Shareholder",
  "Even though you're your own boss": "Even though you're your own boss, you're still a part of a bigger company. Take advantage of it!",

  "The title of the article": "The title of the article goes here and it might be long",
  "Caption goes here": "Caption goes here. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
  "Read More": "Read More",
  "Find out how": "Find out more about how you can create a trusted network with your business partners and provide first-class user experience to your customers.",

  // Login
  "Open the uPort app to login": "Open the uPort app to login",
  "Continue": "Continue",
  "First things first": "First things first",
  "To login scan the QR code with the uPort app": "To login scan the QR code with the uPort app",
  "You're logging in to": "You're logging in to",
  "Tap to login with the uPort app": "Tap to login with the uPort app",
  "Don't have the app? Download it from your store": "Don't have the app? Download it from your store",
  "Issuer": "Issuer",
  "No information requested": "No information requested",
  "This information will be shared with": "This information will be shared with",
  "Waiting for login": "Waiting for login",
  "Refresh": "Refresh",
  "Loading": "Loading",
  "Requested information": "Requested information",

  // Claims
  "regnFormHeading": "Personal Information",
  "regnFormLabel1": "Submit your information to",
  "regnFormLabel2": "to confirm your identity",
  "* indicates required field": "* indicates required field",
  "This field is required": "This field is required",
  "agreeTnC": "I agree to the uPort <1>Terms and Conditions</1>",
  "You must accept the terms and Conditions": "You must accept the terms and Conditions",
  "What's next?": "What's next?",
  "Your information will be verified": "Your information will be verified by one of our identity verification partners. Think about is as a background check but faster and more secure.",
  "Country": "Country",
  "State or Province": "State/Province",
  "Zip Code": "Zip Code",
  "City": "City",
  "Number, Street Name, Apt #": "Number, Street Name, Apt #",
  "Submit": "Submit",

  "Psst, even though it's just a demo": "Psst, even though it's just a demo...",
  "Any data that you enter is securely protected and encrypted": "Any data that you enter is securely protected and encrypted. It will be added as an attestation to your uPort Identity (you can always delete it at any time).",
  "We do not store any of this information and do not reveal it to any party": "We do not store any of this information and do not reveal it to any party.",

  "Good News!": "Good News!",
  "regnSuccessHeading1": "Good News!",
  "regnSuccessHeading2": "What's next?",
  "regnSuccessText1": "Your information has been successfully verified. Your Driver's License is ready to be issued.",
  "regnSuccessText2": "Let's make sure you have an access to your Driver's License whenever and wherever you need it.",
  "regnSuccessText3": "is going to send your new claims to your uPort app.",
  "regnReceiveCTA": "Receive Driver's License",
  "Invalid date of birth": "Invalid date of birth",
  "You must agree to the terms and conditions": "You must agree to the terms and conditions",

  // Attestation
  "Scan this QR Code using the uPort App": "Scan this QR Code using the uPort App",
  "Check your device": "Check your device",
  "Not receiving the request?": "Not receiving the request?",
  "No verified information to receive": "No verified information to receive",
  "This information will be stored in your app": "This information will be stored in your app",
  "Subject": "Subject",
  "Tap to open in a mobile browser": "Tap to open in a mobile browser",
  "You're Interacting with": "You're interacting with",
  "Verified information you'll receive": "Verified information you'll receive",
  "Done": "Done",
  "Back to Home": "Back to Home",
  "Tap 'Accept' in your uPort app to receive your claims": "Tap 'Accept' in your uPort app to receive your claims",

  // Success
  "Congratulations!": "Congratulations!",
  "You received your": "You received your",
  "Your claims are stored in your uPort app": "Your claims are stored in your uPort app.",
  "Services that honor": "Services that honor",
  "Back to Dashboard": "Back to Dashboard",

  // LikeDemo
  "Want to build your own ecosystem?": "Want to build your own ecosystem?",
  "Build user-centric trusted data apps with uPort": "Build user-centric trusted data apps with uPort",
  "Issue, request and verify information about your users": "Issue, request and verify information about your users. Give your users the freedom to manage details about their digital-selves.",
  "View Documentation": "View Documentation",
  "Find out more about how you can create a trusted network": "Find out more about how you can create a trusted network with your business partners and provide first-class user experience to your customer",
  "Build trusted data ecosystem in your city": "Build trusted data ecosystem in your city. Let businesses and organizations thrive while maintaining privacy of the citizens.",
  "Contact Us": "Contact Us",

  // City/ClaimExists
  "regnClaimExists": "It looks like you already have a Driver's License",
  "regnBenefits": "With your Driver's License you have easy and quick access to numerous services and programs in the Ecosystem",

  // Redirect
  "See you later!": "See you later!",
  "You are leaving the dashboard":  "You are leaving the Serto Ecosystem dashboard and will be automatically redirected to",
  "website to continue": "website to continue.",
  "Bye!": "Bye!",

  "Get a digital verification of your": "Get a digital verification of your",
  "Let's make sure you have access to your claims whenever and wherever you need them": "Let's make sure you have access to your claims whenever and wherever you need them."
};
